# Generated by Django 3.2.13 on 2022-10-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pick',
            field=models.CharField(choices=[('BL', 'blue'), ('RE', 'red')], default='BL', max_length=2),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=50),
        ),
    ]
